### PR TITLE
Fix RHCOS links for ARM

### PR DESCRIPTION
**Pull request by yselkowitz**
/cc @sosiouxme﻿

### CODE REVIEW

**Comment by sosiouxme** [comment]
/lgtm
at the moment, the [first nightlies](https://arm64.ocp.releases.ci.openshift.org/releasestream/4.9.0-0.nightly-arm64/release/4.9.0-0.nightly-arm64-2021-05-27-210712) point to [https://releases-rhcos-art.cloud.privileged.psi.redhat.com/?release=48.84.202105262319-0&stream=releases%2Frhcos-4.8-arm64](arm64) which doesn't exist.

**Review by bradmwilliams — APPROVED** [review]
/lgtm

**Pull request merged**
