### PR TITLE
add a new folder to place QE automation tools

### PR DESCRIPTION
**Pull request by jianzhangbjz**
As you may know, there is a `TRT` team set up on the QE side recently to improve the payload release workflow. 
It benefits a lot to work together, so we'd like to place our automation tools in this repo, could you help approve it? Thanks!

### CODE REVIEW

**Comment by bradmwilliams** [comment]
Hi @jianzhangbjz,
We're going to need some more information before possibly approving this PR.  What is `TPT`?  What is the impetus behind the goal to "improve the payload release workflow"?  What are the "tools" that you're planning on putting in this repo?  What is the benefit of these tools being in this repo vs in a repo of their own?  

If possible, could someone, from your team, give an overview of the effort to the folks in our weekly architecture meeting:
SHIP Teams Architecture (CI Testing/Release)
Every Thursday from 11:30am – 12:00p EST
Let me know if you can't see the meeting and I can forward the invite over.
Thanks!

**Comment by jianzhangbjz** [comment]
> We're going to need some more information before possibly approving this PR. What is TPT? 

Hi @bradmwilliams, Sorry, typing mistakenly, I mean `TRT` team. This is an extension of the  [the-technical-release-team](https://docs.ci.openshift.org/docs/release-oversight/the-technical-release-team/) on the QE side.

> What is the impetus behind the goal to "improve the payload release workflow"?

For each payload release, QE needs to do some tests, but for now, some parts are manual, we're automating it.

> What are the "tools" that you're planning on putting in this repo?

Such as triggering the Prow job, getting test results, and updating errata status.

> What is the benefit of these tools being in this repo vs in a repo of their own?

If I'm not wrong, this repo generates OpenShift release/update payloads, and the responsibility of the `TRT QE` side is to test them. In other words, the QE work is the extension of the origin `TRT`. So, we would like to use the same repo.

**Comment by bradmwilliams** [comment]
@jianzhangbjz I had a chat with the TRT folks, this morning, and I think it would be very helpful if you could attend our Architecture meeting tomorrow at 11:30am EST.  If that time is not good, then perhaps we could adjust it to a better time for next week.  Just let us know, thanks!

**Comment by bradmwilliams** [comment]
@jianzhangbjz I can certainly ask. I'll let you know as soon as I hear anything.

**Comment by jianzhangbjz** [comment]
As we discussed in the last weekly architecture meeting, it's better for us to create a new repo under the `openshift` org to store the QE errata tools. So, close it.
/close

**Pull request closed without merging**
