### PR TITLE
Bump test-infra to bfbed413c242

### PR DESCRIPTION
**Pull request by petr-muller**
Prow config code started panicing, I assume something changed in Prow
that's not backwards compatible.

```
I0219 10:01:58.825936       1 main.go:254] Ppc64le releases will be sourced from the following namespaces: ocp-ppc64le, and jobs will be run in ci-release-ppc64le
F0219 10:02:17.147795       1 main.go:116] error: panic loading config: runtime error: invalid memory address or nil pointer dereference
```
The message is not the best, but it looks like https://github.com/kubernetes/test-infra/blob/bfbed413c2425c3d6b8504d2123934ecd5d6bba6/prow/config/config.go#L967

I needed to bump even the `Azure/go-autorest` to v14.2.0, otherwise I
was getting:

```console
$ go mod tidy
go: finding module for package github.com/Azure/go-autorest
github.com/openshift/release-controller/cmd/release-controller imports
	k8s.io/test-infra/prow/config imports
	k8s.io/test-infra/prow/kube imports
	k8s.io/client-go/plugin/pkg/client/auth imports
	k8s.io/client-go/plugin/pkg/client/auth/azure imports
	github.com/Azure/go-autorest/autorest imports
	github.com/Azure/go-autorest: module github.com/Azure/go-autorest@latest found (v14.2.0+incompatible, replaced by github.com/Azure/go-autorest@v12.2.0+incompatible), but does not contain package github.com/Azure/go-autorest
```

### CODE REVIEW

**Comment by petr-muller** [comment]
Needs Go bumped too, which needs to be done in both Dockerfile here (this fixes the image build) and in ci-op config (to fix unit tests, https://github.com/openshift/release/pull/16069).

**Comment by petr-muller** [comment]
This is what I was getting without the bump:
```
hack/build.sh
# sigs.k8s.io/controller-runtime/pkg/manager
vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go:53:2: duplicate method Start
make: *** [build] Error 2
```

**Comment by deads2k** [comment]
unit test failure looks real

```
vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go:53:2: duplicate method Start
FAIL	github.com/openshift/release-controller/cmd/release-controller [build failed]
```

**Comment by petr-muller** [comment]
> unit test failure looks real
That's because unit tests still run go 1.13 - the version comes from ci-op config (https://github.com/openshift/release/pull/16069 will bump it there) The iamges use the Dockerfile which I bump here, hence they pass.

**Comment by smarterclayton** [comment]
Did anyone test this locally or is this "we believe this works"?

**Comment by smarterclayton** [comment]
/lgtm

YOLO

**Comment by alvaroaleman** [comment]
> Did anyone test this locally or is this "we believe this works"?

What kind of local testing would be expected? Is this documented somehow? Would it be worth to add that to CI so ppl not deeply familiar with the release controller can make changes to it and get proper feedback without needing to involve a human?

**Comment by petr-muller** [comment]
> Did anyone test this locally or is this "we believe this works"?

Not familiar with how to test this locally I tested in production, on a OKD r-c first

**Pull request merged**
