### PR TITLE
Update to golang 1.18 and update test-infra

### PR DESCRIPTION
**Pull request by smg247**
`ci-tools` needs an updated `test-infra` dependency, and thus `release-controller` gets one too. Since `test-infra` recently went to golang `1.18` we also need to update it here.

### CODE REVIEW

**Comment by bradmwilliams** [comment]
@smg247 You might need to bump the `.ci-operator.yaml` yaml to 1.18 as well.

**Comment by smg247** [comment]
> @smg247 You might need to bump the `.ci-operator.yaml` yaml to 1.18 as well.

ah yes, good call

**Review by bradmwilliams — APPROVED** [review]

**Comment by smg247** [comment]
...and it appears that we don't have the `golang-1.18` imagestream yet

**Comment by bradmwilliams** [comment]
Chances are this will fail until the `openshift/release:golang-1.18` image is populated:
```
golang-1.18
  updates automatically from registry registry.ci.openshift.org/ci/origin-release:golang-1.18
    prefer registry pullthrough when referencing this tag

  ! error: Import failed (NotFound): dockerimage.image.openshift.io "registry.ci.openshift.org/ci/origin-release:golang-1.18" not found
      10 minutes ago
```

**Comment by smg247** [comment]
> Chances are this will fail until the `openshift/release:golang-1.18` image is populated:
> 
> ```
> golang-1.18
>   updates automatically from registry registry.ci.openshift.org/ci/origin-release:golang-1.18
>     prefer registry pullthrough when referencing this tag
> 
>   ! error: Import failed (NotFound): dockerimage.image.openshift.io "registry.ci.openshift.org/ci/origin-release:golang-1.18" not found
>       10 minutes ago
> ```

yes...I am working on doing that now. I thought that it was ready, but I still needed to wait. I think we are good now so I am going to try again. Sorry for all the noise here...

**Comment by bradmwilliams** [comment]
I figured.  I'm pretty sure the default imagestream import time is 15 mins.
No problem at all!

**Pull request merged**
